### PR TITLE
3.9rc1.ocefpaf

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by mingwandroid** [comment]
OK, I didn't sleep @ocefpaf

**Comment by mingwandroid** [comment]
Needs a little more

**Comment by mingwandroid** [comment]
Fails on Windows with:

```
C:\opt\conda\conda-bld\python-split-3.9.0_2\work\Include\internal\pycore_pylifecycle.h
C:\opt\conda\conda-bld\python-split-3.9.0_2\work\Include\internal\pycore_pymem.h
C:\opt\conda\conda-bld\python-split-3.9.0_2\work\Include\internal\pycore_pystate.h
C:\opt\conda\conda-bld\python-split-3.9.0_2\work\Include\internal\pycore_runtime.h
C:\opt\conda\conda-bld\python-split-3.9.0_2\work\Include\internal\pycore_sysmodule.h
C:\opt\conda\conda-bld\python-split-3.9.0_2\work\Include\internal\pycore_traceback.h
C:\opt\conda\conda-bld\python-split-3.9.0_2\work\Include\internal\pycore_tuple.h
C:\opt\conda\conda-bld\python-split-3.9.0_2\work\Include\internal\pycore_unionobject.h
C:\opt\conda\conda-bld\python-split-3.9.0_2\work\Include\internal\pycore_warnings.h
154 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
The system cannot find the file specified.
Traceback (most recent call last):
  File "C:\opt\conda\Scripts\conda-build-script.py", line 33, in <module>
```

locally, when building with CONDA_BUILD_FROM_SOURCE_CONTROL=yes.

**Comment by ocefpaf** [comment]
Take it easy Ray, there is no rush to get this PR in. I'll work more on it over the weekend.

**Comment by mingwandroid** [comment]
I rebased the patches against git master. Oops. Shall correct shortly.

**Pull request merged**
